ALTER TABLE click_event
    ADD COLUMN browser_version varchar(64),
    ADD COLUMN os_version varchar(64),
    ADD COLUMN country varchar(128),
    ADD COLUMN region_name varchar(128),
    ADD COLUMN city varchar(128),
    ADD COLUMN time_zone varchar(64),
    ADD COLUMN asn varchar(32),
    ADD COLUMN provider varchar(255),
    ADD COLUMN network_type varchar(32),
    ADD COLUMN proxy_status varchar(16) NOT NULL DEFAULT 'unknown',
    ADD COLUMN vpn_status varchar(16) NOT NULL DEFAULT 'unknown',
    ADD COLUMN tor_status varchar(16) NOT NULL DEFAULT 'unknown',
    ADD COLUMN referrer_category varchar(32),
    ADD COLUMN client_hint_platform varchar(64),
    ADD COLUMN client_hint_platform_version varchar(64),
    ADD COLUMN client_hint_mobile varchar(16),
    ADD COLUMN client_hint_model varchar(128),
    ADD COLUMN hour_of_day smallint,
    ADD COLUMN day_of_week varchar(16);
